// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_l75-kXkupKxWdViVW6QMRtEvPL4fUMI',
    appId: '1:1007494287491:web:9133365dd4f8b50de4cbb6',
    messagingSenderId: '1007494287491',
    projectId: 'focusdeck-ffebb',
    authDomain: 'focusdeck-ffebb.firebaseapp.com',
    storageBucket: 'focusdeck-ffebb.firebasestorage.app',
    measurementId: 'G-NTB9W4R8F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6aQHNJYQVa85c6t8rZYPCEx3PiVhSRgg',
    appId: '1:1007494287491:android:db8ce759df5e934de4cbb6',
    messagingSenderId: '1007494287491',
    projectId: 'focusdeck-ffebb',
    storageBucket: 'focusdeck-ffebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzu8MsJVwhmiCbxvMzuRA7vsK41j6MGTk',
    appId: '1:1007494287491:ios:183a3bed9a00aacde4cbb6',
    messagingSenderId: '1007494287491',
    projectId: 'focusdeck-ffebb',
    storageBucket: 'focusdeck-ffebb.firebasestorage.app',
    iosClientId: '1007494287491-a530ippuesan0l9gjfq1634037km4o9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusDeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzu8MsJVwhmiCbxvMzuRA7vsK41j6MGTk',
    appId: '1:1007494287491:ios:183a3bed9a00aacde4cbb6',
    messagingSenderId: '1007494287491',
    projectId: 'focusdeck-ffebb',
    storageBucket: 'focusdeck-ffebb.firebasestorage.app',
    iosClientId: '1007494287491-a530ippuesan0l9gjfq1634037km4o9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusDeck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_l75-kXkupKxWdViVW6QMRtEvPL4fUMI',
    appId: '1:1007494287491:web:9133365dd4f8b50de4cbb6',
    messagingSenderId: '1007494287491',
    projectId: 'focusdeck-ffebb',
    authDomain: 'focusdeck-ffebb.firebaseapp.com',
    storageBucket: 'focusdeck-ffebb.firebasestorage.app',
    measurementId: 'G-NTB9W4R8F5',
  );
}
